t script for the Class Attendance Marking System with SQLite database.
Run this to verify the basic functionality of the system.
"""

import os
import unittest
from unittest.mock import patch
import io
import sys
import sqlite3
import tempfile

# Import the main module
from attendance_system import AttendanceSystem

class TestAttendanceSystem(unittest.TestCase):
        """Test cases for the Attendance System."""

            def setUp(self):
                    """Set up test environment."""
                            # Create a temporary database file for testing
                                    self.db_fd, self.db_path = tempfile.mkstemp()
                                            self.system = AttendanceSystem(self.db_path)
                                                    
                                                            # Add some test students
                                                                    self.system.add_student("John Doe")
                                                                            self.system.add_student("Jane Smith")

                                                                                def tearDown(self):
                                                                                        """Clean up after tests."""
                                                                                                # Close the database connection
                                                                                                        self.system.close_connection()
                                                                                                                
                                                                                                                        # Close and remove the temporary file
                                                                                                                                os.close(self.db_fd)
                                                                                                                                        os.unlink(self.db_path)

                                                                                                                                            def test_add_student(self):
                                                                                                                                                    """Test adding a new student."""
                                                                                                                                                            # Add a new student
                                                                                                                                                                    result = self.system.add_student("Bob Johnson")
                                                                                                                                                                            self.assertTrue(result)
                                                                                                                                                                                    
                                                                                                                                                                                            # Verify the student was added
                                                                                                                                                                                                    students = self.system.get_students()
                                                                                                                                                                                                            student_names = [name for _, name in students]
                                                                                                                                                                                                                    self.assertIn("Bob Johnson", student_names)
                                                                                                                                                                                                                            
                                                                                                                                                                                                                                    # Try adding the same student again
                                                                                                                                                                                                                                            result = self.system.add_student("Bob Johnson")
                                                                                                                                                                                                                                                    self.assertFalse(result)

                                                                                                                                                                                                                                                        def test_mark_attendance(self):
                                                                                                                                                                                                                                                                """Test marking attendance."""
                                                                                                                                                                                                                                                                        # Get the ID of Jane Smith
                                                                                                                                                                                                                                                                                students = self.system.get_students()
                                                                                                                                                                                                                                                                                        jane_id = None
                                                                                                                                                                                                                                                                                                for student_id, name in students:
                                                                                                                                                                                                                                                                                                            if name == "Jane Smith":
                                                                                                                                                                                                                                                                                                                            jane_id = student_id
                                                                                                                                                                                                                                                                                                                                            break
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                            self.assertIsNotNone(jane_id, "Jane Smith should be in the students list")
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                            # Simulate marking attendance for Jane
                                                                                                                                                                                                                                                                                                                                                                                    with patch('builtins.input', side_effect=['2', 'done']):  # Assuming Jane is the 2nd student
                                                                                                                                                                                                                                                                                                                                                                                                self.system.mark_attendance("2025-03-29")
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                # Verify Jane's attendance was marked
                                                                                                                                                                                                                                                                                                                                                                                                                        self.system.cursor.execute(
                                                                                                                                                                                                                                                                                                                                                                                                                                    "SELECT status FROM attendance WHERE student_id = ? AND date = ?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                (jane_id, "2025-03-29")
                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                result = self.system.cursor.fetchone()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.assertIsNotNone(result)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.assertEqual(result[0], "Present")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def test_view_attendance(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """Test viewing attendance records."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # First, mark attendance for a student
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            students = self.system.get_students()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    john_id = None
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for student_id, name in students:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if name == "John Doe":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        john_id = student_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.assertIsNotNone(john_id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Insert attendance record directly
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.system.cursor.execute(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "INSERT INTO attendance (student_id, date, status) VALUES (?, ?, ?)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (john_id, "2025-03-29", "Present")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.system.conn.commit()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Capture output for view_attendance
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        with patch('sys.stdout', new=io.StringIO()) as fake_output:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.system.view_attendance("2025-03-29")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                output = fake_output.getvalue()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Check if the output contains the expected data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.assertIn("John Doe", output)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.assertIn("Present", output)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def test_generate_report(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """Test generating attendance report."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Add attendance records for testing
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                students = self.system.get_students()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for student_id, name in students:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if name == "John Doe":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # John is present on both days
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.system.cursor.execute(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "INSERT INTO attendance (student_id, date, status) VALUES (?, ?, ?)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            (student_id, "2025-03-29", "Present")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.system.cursor.execute(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "INSERT INTO attendance (student_id, date, status) VALUES (?, ?, ?)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    (student_id, "2025-03-30", "Present")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif name == "Jane Smith":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Jane is present on one day
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.system.cursor.execute(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "INSERT INTO attendance (student_id, date, status) VALUES (?, ?, ?)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        (student_id, "2025-03-29", "Present")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.system.conn.commit()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Capture output for generate_report
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with patch('sys.stdout', new=io.StringIO()) as fake_output:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.system.generate_report()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        output = fake_output.getvalue()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Check if the report contains the correct data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.assertIn("John Doe", output)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.assertIn("100.00", output)  # 100% present
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.assertIn("Jane Smith", output)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.assertIn("50.00", output)   # 50% present

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def test_database_initialization(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """Test that the database is initialized with the correct tables."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Check if tables exist
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.system.cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tables = [table[0] for table in self.system.cursor.fetchall()]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.assertIn("students", tables)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.assertIn("attendance", tables)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            unittest.main()


